blank_issues_enabled: false
contact_links:
  - name: ğŸ« ESGI
    url: https://esgi.fr
    about: Our school website
  - name: ğŸ”— 3AL2
    url: https://discord.gg/NdQhYWhRJE
    about: Our class discord server